pipeline {
    agent any

    stages {
        stage('eks deployment repo'){
            steps{
                git branch: 'dev-sec-ops-cicd-pipeline-project-one', url: 'https://github.com/awanmbandi/realworld-microservice-project.git'
            }
        }
        stage('Terraform Init') {
            steps {
                dir('eks-terraform') {
                    sh 'terraform init --reconfigure'
                }
            }
        }
        stage('Terraform Validate') {
            steps {
                dir('eks-terraform') {
                    sh 'terraform validate'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('eks-terraform') {
                    sh 'terraform plan'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('eks-terraform') {
                    sh 'terraform ${action} --auto-approve'
                }
            }
        }
    }
}
